---
# Production environment overrides

env_name: prod

# Stricter SSH for prod
ssh_permit_root_login: "no"
ssh_password_authentication: "no"

# Prod-specific packages
extra_packages: []

# Security settings
fail2ban_enabled: true
